### ISSUE TITLE
Incorrect pose after yeeting an item (MP)

### ISSUE THREAD

**Issue by JyeGuru** [PJ-Mog/VSMod-YEET#7]
When a player yeets something, they get "stuck" in the "Psycho Stabby" pose:
![image](https://user-images.githubusercontent.com/5215014/125169499-d4493b80-e1ed-11eb-8b0d-92106338e3a3.png)

This can be fixed by throwing a stone (or possibly a spear) at which time the character returns to normal until the next time they yeet something. F5 does not show the player like this, only seen by other players.

Repeatable:
 - Join MP server with another player
 - Have them yeet something
 - Observe them attempting to stabby stabby everything
 - Laugh at how hilarious it is with some items:
![image](https://user-images.githubusercontent.com/5215014/125169558-1b373100-e1ee-11eb-8d95-bdefa8bf0f02.png)

**Comment by PJ-Mog** [comment]
@JyeGuru I actually have had a [1.0.2 version ready to go](https://github.com/JapanHasRice/VSMod-YEET/releases/tag/v1.0.2) for a while that I think fixes this. I forget what animation bug I fixed in that version, but I was holding off on releasing until 1.15 got closer to release. (It's probably time to do that, eh?)

**Comment by PJ-Mog** [comment]
Not sure if you want to try that out or not. I have not done any testing with that 1.0.2 release since 1.15.0-pre3, so use at own risk. Otherwise, I'll try to do a proper test over the weekend and officially release.

**Comment by JyeGuru** [comment]
Awesome - we're still on 1.14, should have mentioned that in the report (and probably will be for a while, the game has changed a LOT with 1.15, and will require some preparation for migrating our world)

I'll give 1.0.2 a try next time I do some mod updates on the server. Thanks. :)

**Comment by PJ-Mog** [comment]
@JyeGuru Sorry for the late update. The 1.0.2 release does not fix the issue you're having. I'll have to fix this up for another release

**Comment by PJ-Mog** [comment]
@JyeGuru v1.0.3 is available and fixes this issue. Thank you for reporting and I'm sorry I took so long to fix it!
